### ISSUE TITLE
Bug found while generating PDF

### ISSUE THREAD

**Issue by RuiArmada** [cesium/calendarium#52]
Found a bug while using the "Generate PDF" function. Basically, the generated PDF has some visual bugs that make the time column and day of the week line hard to notice. 

![image](https://user-images.githubusercontent.com/38467452/194939324-84c9d501-fe6c-4903-b6a9-8454454cad50.png)

**Comment by diogogmatos** [comment]
No longer applicable (removed feature), refer to #209.
