### ISSUE TITLE
Bug displaying event 

### ISSUE THREAD

**Issue by MarioRodrigues10** [cesium/calendarium#87]
There's an error when displaying events date, the event is set to be between 5th to 7th of June and inside ```Calendarium``` is displaying 4th to 7th of June.

![image](https://user-images.githubusercontent.com/93675410/223450692-f53b015c-4e84-4248-94c9-4616debdf0b7.png)
![image](https://user-images.githubusercontent.com/93675410/223450857-672a96dc-8a8e-4896-8e4f-2b30a9fefe14.png)

**Comment by RuiL1904** [comment]
That only happens in development. You can see that in production it's correct.
